version: '3'

services:
  db_service:
    container_name: springbootWebfluxDB
    image: mongo:5
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_DATABASE: springboot_webflux_db
    volumes:
      - ./mongo:/data/db
    networks:
      - springboot_webflux_network

  app_service:
    container_name: springbootWebfluxApp
    depends_on:
      - db_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - springboot_webflux_network

networks:
  springboot_webflux_network: